### ISSUE TITLE
Token can be leaked via debug flag

### ISSUE THREAD

**Issue by ZacSweers** [pascalgn/automerge-action#106]
While hidden behind a debug flag, it would be good if this env printing was a little more precise to avoid the risk https://github.com/pascalgn/automerge-action/blob/f81beb99aef41bb55ad072857d43073fba833a98/bin/automerge.js#L63

**Comment by pascalgn** [comment]
I think it's a good point. Do you want to create a PR for it?

**Comment by pascalgn** [comment]
I just had a closer look at it and it doesn't look like the token is printed. Only the following debug output is shown:

```
DEBUG Configuration: {
  mergeLabels: { required: [ 'automerge' ], blocking: [] },
  mergeRemoveLabels: [ '' ],
  mergeMethod: 'merge',
  mergeMethodLabels: [],
  mergeMethodLabelRequired: false,
  mergeForks: true,
  mergeCommitMessage: 'automatic',
  mergeCommitMessageRegex: '',
  mergeFilterAuthor: '',
  mergeRetries: 6,
  mergeRetrySleep: 5000,
  mergeDeleteBranch: false,
  updateLabels: { required: [ 'automerge' ], blocking: [] },
  updateMethod: 'merge',
  updateRetries: 1,
  updateRetrySleep: 5000
}
```

I'm closing this now, but if you think I made a mistake or if you have additional comments, feel free to reopen! 👍
