### ISSUE TITLE
clarification on documentation

### ISSUE THREAD

**Issue by stack72** [pascalgn/automerge-action#110]
Hi

Thanks so much for this project - it's become part of the workflow we use daily now 👍 

Can you clarify what the behaviour of `MERGE_RETRIES` and `MERGE_RETRY_SLEEP` is? Does this keep the action alive for the period of time determined in `MERGE_RETRY_SLEEP`?

Or does this try every X period of time as determined in `MERGE_RETRY_SLEEP` until it exhausts the `MERGE_RETRIES` value? We are using this with a private GitHub repo and don't want to keep an action running for too long as it's something we pay for

Thanks

Paul

**Comment by pascalgn** [comment]
>Or does this try every X period of time as determined in `MERGE_RETRY_SLEEP` until it exhausts the `MERGE_RETRIES` value?
Yes, this one

So if MERGE_RETRIES was 7 and MERGE_RETRY_SLEEP was 2000, then the action would sleep for a total of 7 x 2000 = 14000 ms = 14 seconds maximum. Of course, when the PR is ready for merge earlier, it will not retry the full 7 times

**Comment by stack72** [comment]
thanks @pascalgn
