### ISSUE TITLE
Access PR author in MERGE_COMMIT_MESSAGE

### ISSUE THREAD

**Issue by bilelomrani1** [pascalgn/automerge-action#111]
I would like to add the PR author to the message commit (for credits in the CHANGELOG). The following `MERGE_COMMIT_MESSAGE ` example: 

```
{pullRequest.title} (#{pullRequest.number}). {pullRequest.body}
```

works correctly so I assumed that `pullRequest` is a Pull Request object fetched by [Github's REST API](https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls), and I tried 
```
{pullRequest.title} (#{pullRequest.number}). {pullRequest.body} (@{pullRequest.user.login})
```
but the string is not interpolated.

Is there a way to achieve a similar result?

**Comment by pascalgn** [comment]
This is currently not possible, I'm afraid. Your suggestion to make `pullRequest` a "real" Pull Request object sounds reasonable.

Do you want to provide a PR for this?

**Comment by bilelomrani1** [comment]
I can try providing a PR. I do want to disclaim that, even though it's on my (endless) learning list, I have no experience in Javascript so I may not come up with the most elegant solution. But still, I'll do my best to provide a modest contribution 😄
