### ISSUE TITLE
Automerging only for dependabot

### ISSUE THREAD

**Issue by TobiasBales** [pascalgn/automerge-action#114]
I was trying to set up the automerge-action for dependabot (so that not everybody can just open PRs and get them merged)
and added a filter using `MERGE_FILTER_AUTHOR: "dependabot"`.
I then added another job with my username and it works - this works as expected.

Then I thought about it that the author might be different for apps and so used the GitHub API explorer to look at the login name of dependabot (via one of the PRs it created) but it seems to be correct.
Has anyone else had this issue/found the solution/knows what I might be doing wrong?

Any help would be much appreciated.
The [repository in question](https://github.com/TobiasBales/rails_starter/) with an example [dependabot PR](https://github.com/TobiasBales/rails_starter/pull/80)

**Comment by pascalgn** [comment]
I've added some logging, could you please try with latest version v0.12.0 and see if there is a log message like `PR author 'abc' does not match filter: 123`?

**Comment by TobiasBales** [comment]
Will try - actually dependabot should update the action by itself and it should show up soon

**Comment by TobiasBales** [comment]
That helped, thank you.
Turns out bot users have `[bot]` appended to their name so it is actually `dependabot[bot]`
You might want to add this to the README, maybe? ;)

Thank you again for the quick help, really appreciate it. Going to close this issue now.
