### ISSUE TITLE
Dead lock at waiting another check

### ISSUE THREAD

**Issue by longquanzheng** [pascalgn/automerge-action#116]
Hello I am using the automerge action: https://github.com/uber/cadence/blob/master/.github/workflows/automerge.yml

But when I tried it at https://github.com/uber/cadence/pull/3614
Seem like the check is waiting for each other and hence cannot merge(even manually):
![Screen Shot 2020-10-08 at 5 07 07 PM](https://user-images.githubusercontent.com/4523955/95525731-26bca980-0989-11eb-940f-076edb30b83c.png)

Looks like automerge is waiting for "buildkite/cadence-server/pr Expected — Waiting for status to be reported" 
abut that is also waiting for automerge :( 

In automerge workflow:
```
INFO  Updating PR #3614 Add primrary key to mysql domain_metadata table for replication group
INFO  qlong-mysql-rg-schema HEAD: f921c478271e03df734c91fbaf5cbf57333ea3da
INFO  Rebasing onto master a90f6eecf984f1195b28b4b5a5bda49d16cb3784
INFO  Already up to date: qlong-mysql-rg-schema -> master a90f6eecf984f1195b28b4b5a5bda49d16cb3784
INFO  Merging PR #3614 Add primrary key to mysql domain_metadata table for replication group
INFO  Current PR status: mergeable_state: blocked
```

How can I fix that?

**Comment by longquanzheng** [comment]
looks like it's the issue of the buildkite/cadence-server/pr webhook

**Comment by pascalgn** [comment]
I think you have found the answer. However, feel free to reopen this or create a new issue if there are any other problems! 👍
