### ISSUE TITLE
automerge didn't wait for all checks being passed

### ISSUE THREAD

**Issue by pahud** [pascalgn/automerge-action#118]
Hi

Thanks for this awesome action. I noticed the automerge workflow will not wait all checks being passed  and it just merged immediately. Did I miss any configuration?

https://github.com/aws-samples/aws-cdk-for-k3scluster/pull/96

thanks

**Comment by pascalgn** [comment]
See the README:

>A pull request is considered ready when:
>
>2. the required checks have passed (if enabled in the branch protection rules) and

It only waits for checks that are marked as required

**Comment by pahud** [comment]
thanks for the headsup!
