### ISSUE TITLE
Add configuration to enable/disable deletion of merged branch

### ISSUE THREAD

**Issue by davidelorenzitw** [pascalgn/automerge-action#12]
I'm starting to test this, and it looks great :)

One thing that I'd find useful, though, is the capability to manually configure if the source branch should be or not deleted once the PR is merged.

Reason is, when working in a team (especially in a big one), different people do prefer to keep merged branches for a while, for extra security/personal preferences.
This means that those branches should not be deleted automatically because of a shared setting on this GitHubAction.

Thanks, and great work :)

**Comment by pascalgn** [comment]
GH keeps the branches around for some time and there's the "Restore branch" option to un-delete branches. The local branches are not affected by this action either, of course.

So I don't see much benefit for such an option, but feel free to create a PR for it, of course, I'm not against it! 👍

**Comment by wereHamster** [comment]
You can configure the repository to automatically delete (or not) branches after merge: https://help.github.com/en/articles/managing-the-automatic-deletion-of-branches. That way the logic is kept completely out of any actions which do the merge automation.

**Comment by hugovk** [comment]
I also recommend using the repo config @wereHamster suggested.

Alternatively, there's already an action to cleanup branches after merge:

* https://github.com/jessfraz/branch-cleanup-action

Found via:

* https://github.com/sdras/awesome-actions

**Comment by pascalgn** [comment]
Yes, I thought about it and I think I'll remove this feature, now that GH has implemented it directly! Thanks for the input! 👍
