### ISSUE TITLE
Publish PR comment when giving up

### ISSUE THREAD

**Issue by matthew-limbinar** [pascalgn/automerge-action#124]
It would be nice to be notified when this great and wonderful tool gives up, which could be due to too many retries, merge conflicts, other actions failing, etc. 

It could tie into the existing GitHub PR system by posting a comment, preferably with the reason it gave up. Then I'd automagically get a Slack message (or email, if I'm a caveman still living in the 90s).

**Comment by pascalgn** [comment]
This is merged now via #186. I hope this gives you the options you need, if not please feel free to reopen this issue! 🙏
