### ISSUE TITLE
Question: Why isn't this action a javascript action

### ISSUE THREAD

**Issue by david-gang** [pascalgn/automerge-action#125]
Hi,

As i can see this action is a docker action. Wouldn't it make more sense to have this a javascript action? I can see that the code is javascript code and could be packaged very easily as javascript action. 
What do i miss here ?

Thanks,
David

**Comment by pascalgn** [comment]
There is no reason other than when this action was created, only Docker-based actions were possible.

Do you want to create a PR for it? 🙏

**Comment by david-gang** [comment]
I am not sure i will have time to get to it. I have some thoughts on what it does mean:
* I see that in dockerfile openssl and git is installed. Why is openssl installed? Additionally if this action is converted to javascript action we may assume that git is already installed on the machine
* When converting to javascript action the environment variables may be converted to normal inputs. This is much nicer but a breaking change. Do you want to do this? 
* Do you want to use ncc as build script or commit the node_modules? When using ncc it has to be ensured that it is called after every editing of a file but it is nicer.

**Comment by haldunanil** [comment]
I'm working on getting this out of Docker, will have a PR out soon!

**Comment by parndt** [comment]
@haldunanil thank you! ❤️

**Comment by pascalgn** [comment]
The PR has been merged and it has been released as v0.13.0 👍
