### ISSUE TITLE
Queued automerge / autorebase

### ISSUE THREAD

**Issue by gorner** [pascalgn/automerge-action#13]
It appears this action will automatically update all PRs labelled "automerge" or "autorebase" at once, each time the base branch is updated. Ideally there should be an option whereby the PRs can be queued (e.g. by PR age, or by the time the label was applied) and updated/rebased then merged one at a time, to prevent unnecessary CI runs.

Similar comparable feature: the Mergify GitHub app's [`merge` action](https://doc.mergify.io/examples.html) with `strict: smart`

**Comment by pascalgn** [comment]
Yes, that would definitely be a nice addition, but I don't see me implementing this anytime soon. We almost never have multiple PRs open that could be merged at once, so it's very rare for us to run into the problem. On the other hand, this looks like a non-trivial feature which could take some time to implement.

But of course, feel free to create a PR and I promise to have a look at it in a timely fashion! 👍

**Comment by pascalgn** [comment]
I'm closing this now, but if you have any additional input or need support, feel free to reopen this and/or create a new issue or a PR, of course!
