### ISSUE TITLE
define different merge strategies per branch

### ISSUE THREAD

**Issue by timomayer** [pascalgn/automerge-action#132]
It would be great if different merge strategies per branch could be supported and that always target branch defines the strategy so we can have something like:

develop: squash
master: merge

**Comment by pascalgn** [comment]
I think this is useful, but I don't need this at the moment and I don't see myself implementing this anytime soon.

If you really need this, there is a workaround: GH supports "if" clauses for workflows, so you could define multiple automerge actions, each with different merge configuration options and each with different "if" clauses targeting different branches.

Having it built-in into automerge-action would also be possible, of course, so feel very free to work on this and if you create a PR for it, I will have a look at it in a timely manner!

I will close this issue for now. If you have any new information or need any help, feel free to reopen it!
