### ISSUE TITLE
Question: Third party integrations

### ISSUE THREAD

**Issue by luanraithz** [pascalgn/automerge-action#139]
Today we use this library but some problems appeared on our integration with Jira. 
The issue is illustrated [here](https://community.atlassian.com/t5/Jira-Software-questions/URGENT-Jira-Github-with-quot-automerge-action-quot/qaq-p/1547716#M110407).

Does anybody know any way to workaround that?

**Comment by pascalgn** [comment]
I understand your problem, but I'm afraid this is not the right place for this issue: there is nothing we can do.

It's such a common issue that it's the first item in the _Limitations_ section: https://github.com/pascalgn/automerge-action#limitations

This action (as other integrations) needs to use the API provided by GitHub; we merge a pull request using the normal merge method here: https://github.com/pascalgn/automerge-action/blob/master/lib/merge.js#L329. This will then call GitHub's merge API: https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#merge-a-pull-request

If GitHub triggers other integrations after the merge or not cannot be controlled by this automerge-action; we basically tell GitHub "please merge the PR" but what happens after that is not in our control. Sorry that I don't have any better news!

**Comment by luanraithz** [comment]
Thanks for your response @pascalgn! 

I understood that there is nothing we could do on this library to fix the problem. 

Thanks again! I'm going to close this issue.
