### ISSUE TITLE
required label missing

### ISSUE THREAD

**Issue by yongzhang** [pascalgn/automerge-action#141]
Hi, 

I don't understand why my PR will not be auto merged with required labels, I can confirm I have required labels in the PR.

here're my job steps:
```
    - name: Create PR to update image version
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: test
        branch: test
        delete-branch: true
        title: 'test'
        body: |
          whatever
        labels: |
          ci_triggered
          app_test
          environment_dev
          imagetag_208a92861bea0e9a4a5e68314cf1b1cc09e2d959

    - name: Auto merge successful PRs
      uses: pascalgn/automerge-action@v0.13.0
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "ci_triggered,app_test,environment_dev,imagetag_208a92861bea0e9a4a5e68314cf1b1cc09e2d959"
        MERGE_METHOD: "squash"
        MERGE_DELETE_BRANCH: "true"
```

```
Run pascalgn/automerge-action@v0.13.0
2021-01-19T05:36:00.525Z INFO  Event name: workflow_dispatch
2021-01-19T05:36:01.099Z INFO  Skipping PR update, required label missing: automerge
2021-01-19T05:36:01.100Z INFO  Skipping PR merge, required label missing: ci_triggered
2021-01-19T05:36:01.101Z INFO  Skipping PR merge, required label missing: app_test
2021-01-19T05:36:01.101Z INFO  Skipping PR merge, required label missing: environment_dev
2021-01-19T05:36:01.101Z INFO  Skipping PR merge, required label missing: imagetag_208a92861bea0e9a4a5e68314cf1b1cc09e2d959
```

**Comment by pascalgn** [comment]
Could you try to re-run the action with debug logging? https://github.com/pascalgn/automerge-action/#debugging

What I think is happening is a bug / timing issue with GH: the automerge-action is probably invoked too early, where the PR has already been created, but the labels haven't been assigned yet. With debug output, you should see the API responses from GH, with the labels GH thinks (at the time) the PR has

**Comment by yongzhang** [comment]
I added a dedicated step to run `sleep 60` and it didn't work either, so I changed to call github api using curl instead.

**Comment by EhsanHerai** [comment]
@pascalgn I have the same issue bro

**Comment by JonLegendreSoluta** [comment]
This error is occasionally a red herring when branch protection rules cause an issue with the automerge. Check that the user associated to your token has rights to merge on the target branch.
