### ISSUE TITLE
Know if PR was successfully merged

### ISSUE THREAD

**Issue by vvargas90** [pascalgn/automerge-action#142]
Hi! 

It would be really usefull to know if the action was able to merge the PR or not. I want to send a slack message to inform if PR was automerged or not, and based on the action status I want the message to be one or another. Is it doable? 

Cheers

**Comment by pascalgn** [comment]
FYI, there is an open PR for exactly this issue: #169

**Comment by pascalgn** [comment]
This is merged now! 👍
