### ISSUE TITLE
On-rebase, remove automerge tag(s) defined in the action.

### ISSUE THREAD

**Issue by AraHaan** [pascalgn/automerge-action#143]
I have a pull request that was rebased due to another pull request being auto merged before it, automerge rebased it I think however did not remove the label for it so that way automerge could be executed again.

I locked automerge down to label because I was having issues before with automerge messing up.

take a look at https://github.com/Elskom/Sdk/pull/37

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍

**Comment by AraHaan** [comment]
I mean I fixed it by making automerge handled & automatic pr approval handled by the mergify.io github bot instead.
