### ISSUE TITLE
Can this action support workflow_run?

### ISSUE THREAD

**Issue by jbcpollak** [pascalgn/automerge-action#144]
We are using another action to trigger this one, but GitHub doesn't allow that, so we'd like to use the `on: workflow_run` event condition to trigger this workflow. Would that be possible?

This would help with situations where unit-test execution takes longer than the timeout of this action's retries, so that when we trigger a merge, and then upstream is merges into the PR, we could say `on: workflow_run: "CI Validation"`, which would trigger automerge to run again, once the merge build completes successfully.

**Comment by roryabraham** [comment]
For similar reasons (preventing race conditions), I also want to use this action from a workflow `on: workflow_run`. Perhaps one way to support that would be to provide an optional `pull_request_number` input, and use that in place of the event context to fetch the pull request. Would love to see this feature! If you're open to it, I could create a pull request to provide the support I've described 😄
