### ISSUE TITLE
New commit after a `automerge` label added

### ISSUE THREAD

**Issue by jrbourbeau** [pascalgn/automerge-action#147]
I was wondering what happens if a PR is reviewed / approved and the `automerge` label is added, but before all the required checks complete (e.g. while CI is running), the PR author pushes a new commit and the reviewer doesn't notice the new commit before all the required checks have completed. Does this result in `automerge-action` still merging the PR?

**Comment by pascalgn** [comment]
Yes, as long as the automerge label is there, the automerge-action will try to merge the PR (if all required checks have passed).

In the branch protection rules in GitHub, you can enable the setting "Dismiss stale pull request approvals when new commits are pushed" which will cancel PR approvals when new commits are pushed, maybe this can help you.
