### ISSUE TITLE
dry-run to determine mergability?

### ISSUE THREAD

**Issue by terry-yolabs** [pascalgn/automerge-action#148]
Is it possible to execute this step with a dry-run flag to determine the mergeability?  
I would like to test mergeability with a dry run flag then execute some deployment steps before performing the merge step again without the dry-run flag.

Is something like this possible?

Thank you,
-Terry

**Comment by pascalgn** [comment]
Unfortunately, this isn't possible and I'm afraid there's no easy way to get this information. When writing this action, it would have really helped if this info (can a PR be merged = merge button is "green" in the GitHub web UI) was easily available. The GitHub API provides a flag `mergeable_state` on the PR object, but this is not reliable. Therefore, if you look at e.g. https://github.com/pascalgn/automerge-action/blob/master/lib/merge.js#L227 you will see that we check for some things which mean that the PR is _probably_ mergeable and then just try to merge it (repeatedly). But that means, of course, that the moment we know the PR is mergeable, we also merged it. So I'm afraid this won't help you

**Comment by terry-yolabs** [comment]
I came to the same conclusion.  mergeable_state isn't reliable and can't be used to know the mergeability of a PR with certainty.  I resorted to testing all conditions which caused a prior failed merge. I really wish github would expose more API endpoints.

Thanks for the reply.
-Terry
