### ISSUE TITLE
Merged commit description contains all commit description

### ISSUE THREAD

**Issue by davidelorenzitw** [pascalgn/automerge-action#15]
When merging a PR and squashing all the commits, the resulting commit description contains the PR title + each commit message.

Would it be possible to add a configurable option to decide wether to keep the actual behaviour or allow, for example, only the PR title to go in the merged commit description?

This is what we often do, to keep commit description short and clear.

**Comment by pascalgn** [comment]
Yes, I think this should be possible and it will probably not be too difficult to implement. GH offers the property `commit_message` in the merge API: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

So we would need to
1. add a new configuration option here: https://github.com/pascalgn/automerge-action/blob/master/bin/automerge.js#L55 and
2. add the commit_message property from above in https://github.com/pascalgn/automerge-action/blob/master/lib/merge.js#L107

Feel free to create a PR for it, if you like! 👍
