### ISSUE TITLE
Support `workflow_run` events

### ISSUE THREAD

**Issue by apexskier** [pascalgn/automerge-action#155]
I'm attempting to use this workflow after being triggered by `workflow_run`, as described in https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.

However, I get the error `invalid event type: workflow_run` ([from here](https://github.com/pascalgn/automerge-action/blob/39d831e1bb389bd242626bc25d4060064a97181c/lib/api.js#L83)).

You can see how I'm using this at https://github.com/apexskier/nova-json-language-server/blob/ea98f31ada6c0a0561bfbee45dc92c2bc621687b/.github/workflows/dependencies.yml.

From what I see in the code, `workflow_run` could be supported by checking `github.event.workflow_run.event` and delegating to some of the other executors.

**Comment by apexskier** [comment]
Whoops, just found https://github.com/pascalgn/automerge-action/issues/144

**Comment by pascalgn** [comment]
Thanks for the PR, it's merged now! 👍
