### ISSUE TITLE
Branch deletion doesn't take actual protection rules into account

### ISSUE THREAD

**Issue by invakid404** [pascalgn/automerge-action#157]
Hello, we've been using this action for a while now and I've recently realized that the protected branch check ignores all protected branches, regardless of whether they are explicitly allowed to be deleted. I'm not sure whether this is expected behavior or not, but it sounds reasonable to me that if "Allow deletions" is enabled, the action should delete the branch, regardless of whether it counts as "protected".

**Comment by pascalgn** [comment]
Yes, this is a bug. At the time this check was written, GH didn't have the "Allow deletions" option and all protected branches were treated as "don't allow deletion." Do you want to provide a PR for this?

**Comment by invakid404** [comment]
Sure, I can give it a go.

**Comment by invakid404** [comment]
PR open, #162. Take a look whenever you can @pascalgn.

**Comment by invakid404** [comment]
I can confirm that branch deletion now works properly after #162 was merged, so I'm closing this issue.
