### ISSUE TITLE
Update PR but don't merge?

### ISSUE THREAD

**Issue by hugovk** [pascalgn/automerge-action#16]
> `automerge` means that changes from the base branch will automatically be merged into the pull request, but only when "Require branches to be up to date before merging" is enabled in the branch protection rules. When the PR is ready, it will automatically be merged.

When an `automerge` label is added, we'd like for the base branch to be automatically merged into the PR. The action does this ✅

But, when ready, we'd like to hold off the PR itself being automatically merged, and would prefer a human to decide when to press the button.

* Reason: we want to decide when things are merged and consequently deployed.

Is it possible to configure the action to _not_ do the second part?

Thank you!

**Comment by pascalgn** [comment]
We have a similar workflow except we use `autorebase` instead, which rebases instead of merging.

What we do is we configure a branch protection rule in GitHub, saying that 1 review is required to be merged. Then the original author can add the "autorebase" label when they're done and as soon as someone gives an approving PR review in GitHub, the PR will be merged.

If you don't want to use this feature of GH, you could have another condition, for example an additional label `approve`, that is necessary for merging. But for this to work, we would need some changes in the code because in api.js, there is a check for labels _before_ anything else is done:
https://github.com/pascalgn/automerge-action/blob/master/lib/api.js#L146
And only if that check is successful, the PR will be updated, but only if the PR state is "behind". I have often seen it in the past that GH reports the PR state as "unknown" when there's still actions running, so this might also need to be adapted:
https://github.com/pascalgn/automerge-action/blob/master/lib/update.js#L54

**Comment by csi-lk** [comment]
Hey @pascalgn we have a similar requirement where we don't want to auto merge but the auto rebasing is pretty handy, would you be happy for me to make these changes that you've talked about and maybe come up with a new option like `AUTOREBASE_ONLY` for this functionality? Or do you want to keep this package as is and I split that out into a separate action? (can do but would be a lot of code reuse based on reading through the source)

**Comment by pascalgn** [comment]
Yeah, a similar requirement was also requested in #20 where I replied about splitting this project into two separate ones. However, I thought about it in the last days (but forgot to post here) and I now think it's better to keep this action as one.

I think the cleanest and hopefully also most obvious way to implement the change is to add a new option to `MERGE_METHOD` of just `"none"`, so when people set `MERGE_METHOD: none`, the action will update the branch, but not merge.

If you want to give it a go, sure, I'm happy to review any PRs! 👍

**Comment by blake-newman** [comment]
@pascalgn I want to provide some additional thoughts here.

My main thoughts on this topic is that there seems to be a requirement for autorebasing without merging. However there is a missing use case worth considering, that the above solution does not currently support. 

There could be a case, and infact a likely case in some of our Engineering team projects workflow to separate the flows but still utilise both flows. The would be two separate labels. `auto-update` and `auto-merge`

In 90% of cases `auto-update-and-merge` is useful however there is the edge case that a PR may be almost ready and to assist with the merging it can be given the `auto-update` flag, however it's sensitive and may need more reviewers than the minimum required so the `auto-merge` / `auto-update-and-merge` flags are risky. 

Given the above there seems to be several flows to account for:

`auto-update-and-merge`: update and merge once all status checks pass

`auto-update`: keep the branch up to date (may be there is a queue of PRs that take priority, however soon as they are through this PR can go and will be up to date)

`auto-merge`: merge the branch as soon as PR status checks have passed. Can be used in repository where keeping up to date to target branch is not necessary, and can also be used along side `auto-merge` if needed. 

Further to add to the conversation, the usage of `AUTOREBASE` `AUTOMERGE` naming is slightly confusing to the naked eye as both flags could be confused with `MERGE_METHOD` strategy. My suggestion would be to create breaking change to rename to following to allow for the three workflows and clear up the naming: `AUTO_UPDATE` `AUTO_MERGE` `AUTO_UPDATE_MERGE` `MERGE_METHOD`

My suggestions here are opinionated based on current missing functionality reported by one of our teams, and loosely held. Would love to here your thoughts

**Comment by pascalgn** [comment]
Thanks for the detailed analysis anyone! I see the usefulness of these workflows and I do agree that it makes sense to change the current logic.

## Configuration

My suggestion would be to change the configuration in the following way, to hopefully make it more consistent...

### Methods

- `MERGE_METHOD`: Which method to use when merging the pull request (`merge`/`rebase`/`squash`), this is exactly the same as before
- `UPDATE_METHOD`: (**new**) Which method to use to _update_ the pull request (`merge`/`rebase`)

### Labels

- `MERGE_LABEL`: (**new**) When this label is assigned to a PR, it will be merged (using `MERGE_METHOD`) when it's ready (this replaces the old `AUTOMERGE` and `AUTOREBASE` config)
- `UPDATE_LABEL`: (**new**) When this label is assigned to a PR, it will be updated regularly (using `UPDATE_METHOD`)
- `MERGE_AND_UPDATE_LABEL`: (**new**) When this label is assigned to a PR, it will be updated regularly _and_ merged when it's ready

## Defaults

With the changed configuration, the default values also need to be adapted slightly.

- `MERGE_METHOD`: `merge` (as before)
- `UPDATE_METHOD`: Unsure, probably also `merge`, as that's also GH's default action (when the PR is behind and clicking the "Update branch" button)

Regarding labels, I can see two possible defaults:

### A

- `MERGE_LABEL`: `""` (none)
- `UPDATE_LABEL`: `""` (none)
- `MERGE_AND_UPDATE_LABEL`: `automerge`

### B

- `MERGE_LABEL`: `automerge`
- `UPDATE_LABEL`: `autoupdate`
- `MERGE_AND_UPDATE_LABEL`: `""` (none)

I think I would prefer _A_, as it's probably (?) what most people want, but _B_ would be a bit more explicit maybe.

Hopefully, this should cover all possible use cases. Let me know what you think!

**Comment by blake-newman** [comment]
I have created a PR that should aim to cover the above changes; using defaults of **A**.

**Comment by blake-newman** [comment]
Being able to accomplish the full workflow as desired GitHub actions needs to be also able to trigger based on a PR mergable state (which currently affects the functionality now)

I have posted a message to the GitHub community: https://github.community/t5/GitHub-Actions/New-Trigger-is-mergable-state/m-p/36908

**Comment by pascalgn** [comment]
I've merged the PR from @blake-newman now (thanks a lot again!) and published a release. I also tested it and it works fine! 👍

If you find any issues with it, let me know!

**Comment by pascalgn** [comment]
I've just released https://github.com/pascalgn/automerge-action/releases/tag/v0.6.0 which will hopefully make the configuration even clearer (configuration `LABELS` and `MERGE_LABEL`/`UPDATE_LABEL` has now been "merged")
