### ISSUE TITLE
ERROR Cannot read property 'owner' of undefined

### ISSUE THREAD

**Issue by cmalard** [pascalgn/automerge-action#161]
```
Run pascalgn/automerge-action@v0.14.2
  env:
    GITHUB_TOKEN: ***
    PULL_REQUEST: 5549
    MERGE_METHOD: rebase
2021-06-24T08:05:47.855Z INFO  Parsing PULL_REQUEST input: 5549
2021-06-24T08:05:47.860Z INFO  Event name: schedule
2021-06-24T08:05:47.860Z ERROR Cannot read property 'owner' of undefined
```

I don't have many more datas, I'll try to debug but if you have any inputs... ;-)

**Comment by pascalgn** [comment]
I think it's because you have given `PULL_REQUEST: 5549`. This option is not intended to be used together with schedule

**Comment by cmalard** [comment]
Thanks for following up Pascal :-)

I use it just after opening a PR with `repo-sync/pull-request@v2` ;-)
(I do that to update automatically some translations files)

Is it wrong use, tricky to fix or may I help? :beers:

**Comment by pascalgn** [comment]
I think simply removing the `PULL_REQUEST: 5549` line will already be enough 👍
