### ISSUE TITLE
Github token not found on PR's created by dependabot [potential bug]

### ISSUE THREAD

**Issue by jeswr** [pascalgn/automerge-action#165]
I'm having the following issue in several repositories. 

Whenever a PR is made by dependabot, the auto-merge action fails with error that the Github token was not set (for instance https://github.com/jeswr/hylar-core/pull/125/checks?check_run_id=3025607827). However, for PR's that I have created in the same repository the action runs fine (https://github.com/jeswr/hylar-core/runs/3025583738)

**Comment by pascalgn** [comment]
I believe this is the same issue as mentioned here: https://github.com/pascalgn/automerge-action/issues/150#issuecomment-890815491 and explained a bit more here: https://github.com/jonaskello/eslint-plugin-functional/issues/253#issuecomment-890952443
