### ISSUE TITLE
Does NOT merge if there's a comment in the PR :(

### ISSUE THREAD

**Issue by PovilasAtPoq** [pascalgn/automerge-action#168]
My PR has 2 approvals out of two required. That includes the code owner review (1 out of  1 required). The build is success, but it is NOT merging. That's what the log is saying
![image](https://user-images.githubusercontent.com/44364754/129888879-6ee5bbfb-9849-4c9e-a777-fffb64de08f3.png)

It should ignore comments. Only if someone requests for changes, then it should not merge. But comments are comments and it's fine to merge. Moreover, I tried marking all the comments as resolved, that didn't change anything and it was still not being merged.

**Is this a bug or there's a configuration setting to merge in situations like this?**

-----

_Also please update documentation to include that PRs with comments will not be merged:_
![image](https://user-images.githubusercontent.com/44364754/129889236-4b9445fc-5b29-4a41-8274-67eec80e6310.png)
https://github.com/pascalgn/automerge-action

-----

Screenshot of my checks:
![image](https://user-images.githubusercontent.com/44364754/129889465-890f058e-de26-4c19-bec5-0fc576a95e1c.png)

**Comment by pascalgn** [comment]
My guess is that the event from the screenshot is from a PR review which was not an approval but simply comments. There should be other events that triggered the automerge-action, one of those will not have the "Review state is not approved" message

**Comment by PovilasAtPoq** [comment]
@pascalgn 
> My guess is that the event from the screenshot is from a PR review which was not an approval but simply comments.

You can clearly see in the screenshot that this has passed all the requirements according to GitHub. It has two approvals (we require two). It has code owner approval. And build is a success as well. The button is green for merging.

automerger should follow the same logic as GitHub.

>There should be other events that triggered the automerge-action, one of those will not have the "Review state is not approved" message

This should not matter. Comment should not stop the merge if all the merging conditions is met as per screenshot

**Comment by pascalgn** [comment]
The automerge-action run from your screenshot is irrelevant, because it was triggered by a PR review which was only a comment, not an approval. There are other, relevant automerge-action runs, which have been triggered by PR approvals or successful builds. You need to have a look into the output of these runs to figure out why the PR wasn't merged.
