### ISSUE TITLE
RELEVANT_ACTIONS seems to be a subset of the `types` the docs say we should use

### ISSUE THREAD

**Issue by jmhodges** [pascalgn/automerge-action#17]
In https://github.com/pascalgn/automerge-action/blob/66c8c72c293f9a51cc8e8d5240613df47a019f80/lib/api.js#L7, the RELEVANT_ACTIONS which are used in the pull request update check are a subset of the ones the README says to use[1].

I might have missed an important bit somewhere, but this seems to be wrong and we'd like the complete list?

[1] Specifically,
```
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
```

**Comment by pascalgn** [comment]
Yes, good point! Would you like to create a PR for this?

**Comment by jmhodges** [comment]
On it!

**Comment by jmhodges** [comment]
Thanks!
