### ISSUE TITLE
feature request: remove the extended description before merge

### ISSUE THREAD

**Issue by ethanneff** [pascalgn/automerge-action#174]
Can we have an option to remove the extended description before merge? Typically, this is just the commit titles which are not very useful. This is the highlighted section in the attached image. 

<img width="602" alt="Screen Shot 2021-11-13 at 9 02 39 AM" src="https://user-images.githubusercontent.com/2933593/141652441-118bf6c8-1861-46a6-a189-00335b28a896.png">

**Comment by pascalgn** [comment]
There is the option `MERGE_COMMIT_MESSAGE` would that help already?
