### ISSUE TITLE
Set non-successful exit code when retries exhaust

### ISSUE THREAD

**Issue by nicholaspufal** [pascalgn/automerge-action#176]
Hey there, thank you for your work on this :)

I've noticed that these days when the action fails it simply logs the failure [1]. I would like to understand your train of thought here as I think instead that line of code should be signalling that the action has failed, preventing subsequent steps in a workflow from being executed (something [along the lines of this](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions#setting-a-failure-exit-code-in-a-javascript-action) I think)

[1] https://github.com/pascalgn/automerge-action/blob/main/lib/merge.js#L245

**Comment by AndrewGable** [comment]
I agree this would be helpful

**Comment by pascalgn** [comment]
There is now a new option for this, see #177
