### ISSUE TITLE
Encounter error with Github App Token

### ISSUE THREAD

**Issue by travisgan** [pascalgn/automerge-action#178]
The The action encounters error when using GitHub App Token as GITHUB_TOKEN. Using the default GitHub Action Token or PAT works fine. The GitHub App Token is obtained like this, https://github.com/marketplace/actions/github-app-token.

It throws this error when using GitHub App Token,
ERROR Resource not accessible by integration

Have tried granting the GitHub App different permissions but still same errors. The GitHub App also added as member to 'Restrict who can push to matching branches'. 

GitHub Action Setup

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Auto Merge PR 
        uses: "pascalgn/automerge-action@v0.14.3" 
        env: 
           GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
           MERGE_LABELS: "automerge" 
           UPDATE_LABELS: "automerge" 
           MERGE_DELETE_BRANCH: true

**Comment by pascalgn** [comment]
In the README there's a section about debugging: https://github.com/pascalgn/automerge-action#debugging This should also print all requests being made + responses, so maybe that's something that could help you find the issue?

**Comment by travisgan** [comment]
It appears that it was failing for other unknown reason. Reconfigured it from scratch and it works with Github app token. Thanks.
