### ISSUE TITLE
A PR with many comments may be considered unapproved

### ISSUE THREAD

**Issue by jonathanperret** [pascalgn/automerge-action#189]
We have configured `pascalgn/automerge-action` to require 1 review approval before merging a PR. But the action occasionnally refuses to merge a PR that has the required number of approvals, such as this one: https://github.com/1024pix/pix/pull/4407

Looking into it, we found out that because of pagination in the Github REST API, only the first 30 "reviews" (in the Github API, comments on the PR are returned from the `reviews` endpoint as well with `state === "COMMENTED"`) were considered and therefore, if those did not include enough `APPROVED` reviews the check would fail.

We have a fix that uses a helper method in Octokit, a PR is incoming.

**Comment by pascalgn** [comment]
This is fixed now thanks to your PR! 👍

**Comment by njain1102** [comment]
@pascalgn can you specify which key are you using to do this?
