### ISSUE TITLE
What does BASE_BRANCHES do?

### ISSUE THREAD

**Issue by iUnstable0** [pascalgn/automerge-action#207]
I don't get it what you mean by "restricted in terms of base branches". what does it mean? and what happens if I have the branch "main" in this env?

**Comment by pascalgn** [comment]
If you search for "base branch" here you will get some information that will hopefully help you! https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
