### ISSUE TITLE
Gotcha for new repos

### ISSUE THREAD

**Issue by rbren** [pascalgn/automerge-action#214]
For this action to work, it seems you need to change some settings under Repo -> Settings -> GitHub Actions

This might be a new setting, as I haven't seen it documented here or in similar plugins. Might want to add this to the README.
<img width="836" alt="Screenshot 2023-02-20 at 9 55 30 PM" src="https://user-images.githubusercontent.com/7611973/220236146-595c3769-1f64-49cf-8f30-5f63b3dd5053.png">

**Comment by pascalgn** [comment]
That would be possible, but I think the better way would be to use https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

I believe adding

```yaml
permissions:
  contents: write
```

to the example workflows in the README should be enough...

**Comment by pascalgn** [comment]
I've updated the README, so I think this is fixed now.
