### ISSUE TITLE
Document what happens when the autorebase fails?

### ISSUE THREAD

**Issue by bjchambers** [pascalgn/automerge-action#22]
One concern we have is about the behavior of this action when the autorebase fails. Does it update the PR with broken code? Does it report a useful message making it clear that manual intervention is necessary, etc.

As far as I can tell, it looks like this will reject the promise saying that the rebase failed:
https://github.com/pascalgn/automerge-action/blob/master/lib/git.js#L49

Which I think will cause the action to fail with `exitCode` = 1, and log the error. I assume (but am not sure) that that message will be easy to diagnose in the GitHub PR?

Documentation confirming this behavior (and maybe a screenshot!) would be a great contribution to the docs!

**Comment by pascalgn** [comment]
Yes, `git rebase` exits with code 1 when the rebase operation failed and that will also be reported by this action!

I will consider adding this to the documentation.

**Comment by pascalgn** [comment]
I have updated the documentation! 👍
