### ISSUE TITLE
Update more than 10 PRs in a run

### ISSUE THREAD

**Issue by taobojlen** [pascalgn/automerge-action#261]
We use this action to run daily and merge a PR that will cut a new release. We regularly get results like this:
```
2024-04-09T14:54:18.206Z INFO  Action result: [
  { mergeResult: 'skipped', pullRequestNumber: 5642 },
  { mergeResult: 'skipped', pullRequestNumber: 5521 },
  { mergeResult: 'skipped', pullRequestNumber: 5520 },
  { mergeResult: 'skipped', pullRequestNumber: 5517 },
  { mergeResult: 'skipped', pullRequestNumber: 5516 },
  { mergeResult: 'skipped', pullRequestNumber: 5637 },
  { mergeResult: 'skipped', pullRequestNumber: 5629 },
  { mergeResult: 'skipped', pullRequestNumber: 5635 },
  { mergeResult: 'skipped', pullRequestNumber: 5626 },
  { mergeResult: 'skipped', pullRequestNumber: 5636 }
]
2024-04-09T14:54:18.207Z INFO  More than one result, using  first result for action output
```

Where, even though we do have a PR that matches the conditions, nothing gets merged. It looks like this action limits itself to running on 10 PRs at a time. Is there a way to increase the `MAX_PR_COUNT` so *all* our PRs get evaluated when the action runs?

**Comment by laurent22** [comment]
I have this issue too. Did you ever find a fix for it?

**Comment by laurent22** [comment]
Exposing `MAX_PR_COUNT` as an env variable should be relatively easy. @pascalgn would you accept a PR for this?

**Comment by pascalgn** [comment]
Sure! 👍
