### ISSUE TITLE
How can I change the RETRIES and RETRY_SLEEP

### ISSUE THREAD

**Issue by buo** [pascalgn/automerge-action#30]
Some of my status checks take longer than one minute, so the auto-merge action always fails to merge as follows:

```
INFO  Failed to merge PR: Required status check "Run Tests" is in progress.
INFO  Retrying after 10000 ms ... (1/6)
INFO  Failed to merge PR: Required status check "Run Tests" is in progress.
INFO  Retrying after 10000 ms ... (2/6)
INFO  Failed to merge PR: Required status check "Run Tests" is in progress.
INFO  Retrying after 10000 ms ... (3/6)
INFO  Failed to merge PR: Required status check "Run Tests" is in progress.
INFO  Retrying after 10000 ms ... (4/6)
INFO  Failed to merge PR: Required status check "Run Tests" is in progress.
INFO  Retrying after 10000 ms ... (5/6)
INFO  Failed to merge PR: Required status check "Run Tests" is in progress.
INFO  Retrying after 10000 ms ... (6/6)
INFO  Failed to merge PR: Required status check "Run Tests" is in progress.
INFO  PR could not be merged after 6 tries
```

Here is my workflow:

```yaml
name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@733fcc62d711705eae9cd66fcf49c93c1d1a98c6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          UPDATE_LABELS: automerge
          UPDATE_METHOD: rebase
```

It would be great if I can change the RETRIES and RETRY_SLEEP settings. :)

**Comment by buo** [comment]
I found this issue is also related to issue #14.

**Comment by pascalgn** [comment]
Yes, it's a good point! I created a new release [v0.6.1](https://github.com/pascalgn/automerge-action/releases/tag/v0.6.1) with two new options.

Please note that _I think_ GH is billing the plain minutes an action runs, so even if the action is sleeping, the minutes could still count against your monthly limits!

The current defaults are 6 retries and 10s sleep, so overall this action will sleep 1 minute when the PR is not ready. Now I'm not so sure about this, especially regarding the fact that it affects the billed minutes, so I'm thinking about setting the default to 0 retries...

**Comment by buo** [comment]
@pascalgn Thank you for the quick fix! Although it seems like a hack, it's helpful for my case.
