### ISSUE TITLE
This action creates lot of checks

### ISSUE THREAD

**Issue by dusan-dragon** [pascalgn/automerge-action#31]
Hi first thanks for your work it is awesome.

Currently the action will create a long list of the checks. For example when you add a multiple labels, it will add one check for one label.
Would it be possible to show always only one check in the checklist?
Same as circle ci is doing - so even when you will run the check multiple times, there is always only one entry for it.

**Comment by pascalgn** [comment]
I'm afraid that's a general limitation of GH actions, so you may need to contact GH support or have a look at the https://github.community/ forum.

If there is in fact a way to reduce the amount of checks, I would be happy to implement it!
