### ISSUE TITLE
Auto deletion of branches doesn't seem to work

### ISSUE THREAD

**Issue by jamiepinheiro** [pascalgn/automerge-action#32]
Even with the setting on in the repo settings, branches are not being deleted. I'm wondering if this is a GitHub Api issue or an issue with the action?

**Comment by ymwymw** [comment]
We are having this issue as well

**Comment by jamiepinheiro** [comment]
Confirmed that merging a pull request via the V3 api follows the repos rules. @pascalgn Any idea if your action does anything differently :)

**Comment by pascalgn** [comment]
The action just calls `merge`: https://github.com/pascalgn/automerge-action/blob/master/lib/merge.js#L175

I'm pretty sure it's an issue on GH's side. I ran the action locally yesterday, for testing the MERGE_RETRY parameters and the branch was deleted successfully. To be honest, I'm not particularly surprised, I've ran into a lot of small bugs with the GH actions so far.

If you find any issues, I'm happy to fix it, but I think this is an issue on GH's side.

**Comment by pascalgn** [comment]
I noticed that it's not just sometimes working, sometimes not working, but it seems to never work anymore. I created a PR for it, no full release yet, but I still have a little hope that GH will fix this issue in the next days.

In the meantime, you should be able to use this version, which re-adds the previously removed feature of branch deletion after merge:

```yaml
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@8bab27d2212be1b3a0767ee5ee58f7a255b38812"
```

**Comment by jamiepinheiro** [comment]
Aah okay i see, thanks for jumping on this very quickly! Unfortunately we also using the retry stuff you just added, so just gonna wait on the PR merging. Thanks :)

**Comment by pascalgn** [comment]
The PR is based on the latest master, so the retry configuration should also be included! 👍

**Comment by jamiepinheiro** [comment]
Cool! Is there any blocker on merging #33 ?

**Comment by pascalgn** [comment]
Even though GH support never got back to me, I think this has been fixed now. At least we had a few PRs closed where the branches were deleted, too. Can anyone confirm this?

**Comment by pascalgn** [comment]
I'm closing this now, but feel free to reopen it if you're facing problems again!

**Comment by pascalgn** [comment]
So I just tested it in a private repository and for a private repository on my personal account the automatic branch deletion didn't work. GH support, as usual, wasn't helpful either.

So I've now added a new option MERGE_DELETE_BRANCH (see current README), with default false. Set it like `MERGE_DELETE_BRANCH: "true"` to have the action delete branches after merge!

**Comment by karfau** [comment]
After three month of mail contact with github support (just 6 mails in total), they finally confirmed the issue. I asked them for a timeline will update here in case they reply.
Thx for the option as a work around!

**Comment by karfau** [comment]
I recieved this mail on the first of February:
> Thanks for hanging in there. We received an update internally that we'd like to share here. Our engineers deployed an update that ensures that pull requests merged by GitHub App installations (including the GitHub Actions App via the GITHUB_TOKEN) should be automatically deleted.
> 
> If you're seeing any behavior to the contrary, you're welcome to write back referencing an example in the form of a public repository and we'll do our best to help.

In case you have any public example at hand let me know, so I can forward the information :)

**Comment by pascalgn** [comment]
The funny thing is that I never experienced issues with public repositories. For me, the issue only occurred in private repositories, so even if I see any issues again, I'm quite sure it won't be in a public repository. But let's just hope that it's fixed now :) Thanks for letting me know!

**Comment by karfau** [comment]
Also with your action when the deletion is enabled, I will not invest time to disable it, just to check if it's fixed...
