### ISSUE TITLE
Support for on.schedule.cron?

### ISSUE THREAD

**Issue by Mike-EEE** [pascalgn/automerge-action#37]
Hey there... cool action. :)

I am wanting to use it to automerge generated CHANGELOGs as part of our release management.  To do so, I am having to create a pull request.  However, [due to this issue](https://github.com/peter-evans/create-pull-request/issues/48) no event gets fired.

Not a fan of personal access tokens, I started thinking... why not use `on.schedule.cron`?  I tried and it is not a supported event with this action, apparently:
https://github.com/ExtendedXmlSerializer/NextRelease/commit/78faf75f6375216bf65e55825dc26c3f567fa9a5/checks?check_suite_id=341442778

So I wanted to reach out here to see if it might be possible to support this event or am I off my rocker (again 😆)?

Thank you for any consideration/assistance. 👍

**Comment by pascalgn** [comment]
Sorry, I read this but forgot to reply! 😇 Yes, it's a good idea, and shouldn't be a big change! 👍

If you want, you can take a shot at it, otherwise I will do it when I find the time!

**Comment by Mike-EEE** [comment]
Cool!  I could do a PR but it would mean testing it on my side, which would also mean finding some way of hosting it if I am not mistaken.

I am actually in the middle of building my own Probot app now... once I have that squared away I will have a better idea of how to tackle this.

**Comment by pascalgn** [comment]
@Mike-EEE I created PR #39 for it, but I currently don't have time to test it. If you want to try it out, you can use the commit from the PR like this:

```yaml
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@8744297c4b2d2a54c03017838422a0265c4b8df4"
```

**Comment by Mike-EEE** [comment]
Wow it is sooooo cool that you can point actions to commits.  It's like building webservice by hash. 😆  So interesting!

Excitement aside, I am afraid the new coolness produces another error:

https://github.com/ExtendedXmlSerializer/NextRelease/commit/5ef89db8899ad78d916c7eff562a0f1a6cd1bd03/checks?check_suite_id=350752924

Looks like it's complaining about the `owner` property.

```
ERROR Cannot read property 'owner' of undefined
```

I appreciate the efforts, though!  I hope to be able to take a look into this once I wrap up my own app. 🤞

**Comment by pascalgn** [comment]
Yeah, unfortunately the schedule event looks much different than the other events... I think I fixed it now, but you need to use a different commit, it's `75ca70eb25b33837664f25d6270d20b629d23614`

**Comment by Mike-EEE** [comment]
SUCCESS!!!

https://github.com/ExtendedXmlSerializer/NextRelease/commit/959614d9e72c08f80d7e71a0e52265a42ed91c75/checks?check_suite_id=351475090

![](https://media1.tenor.com/images/396460a8255e020f0d22f186051018a8/tenor.gif?itemid=7441740)

Thank you so much!

**Comment by pascalgn** [comment]
@Mike-EEE I have merged this PR into master now! After some time, I will delete the branch, so the commit you're probably referencing now will be gone. Please update your automerge config file to reference the latest commit (from the current README), so that you won't run into any problems!

**Comment by Mike-EEE** [comment]
Great!  Thanks for the heads up and the efforts, @pascalgn. 👍
