### ISSUE TITLE
Workflow doesn't run when pull request is created by another workflow

### ISSUE THREAD

**Issue by bruffridge** [pascalgn/automerge-action#40]
Any ideas why?

Details including code snippets on github community:
https://github.community/t5/GitHub-Actions/Workflow-doesn-t-run-on-pull-request-when-pull-request-is/td-p/40878

**Comment by pascalgn** [comment]
This seems to be the same issue as in #34 and #37

**Comment by pascalgn** [comment]
I have added a new item to the "Limitations" section in the README! 👍

**Comment by bruffridge** [comment]
Thanks! I'll figure out some other way then.
