### ISSUE TITLE
Do not retry if approving review is required.

### ISSUE THREAD

**Issue by ymwymw** [pascalgn/automerge-action#41]
It would seem that it makes sense to retry if a required check hasn't completed, but not if a review is required. Once a reviewer approves it would generate a new Action.

**Comment by ymwymw** [comment]
`INFO  Failed to merge PR: Required status check "build" is in progress. At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (5/17)
INFO  Failed to merge PR: Required status check "build" is in progress. At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (6/17)
INFO  Failed to merge PR: Required status check "build" is in progress. At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (7/17)
INFO  Failed to merge PR: Required status check "build" is in progress. At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (8/17)
INFO  Failed to merge PR: Required status check "build" is in progress. At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (9/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (10/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (11/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (12/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (13/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (14/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (15/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (16/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  Retrying after 10000 ms ... (17/17)
INFO  Failed to merge PR: At least 1 approving review is required by reviewers with write access.
INFO  PR could not be merged after 17 tries`

**Comment by pascalgn** [comment]
Yes, good point! Unfortunately, the GH API doesn't provide an easy way to figure out why/if a PR can be merged (if you do find one, please let me know!). So for now, I will just look at the error message and stop retrying when it contains `approving review is required by reviewers` or similar

**Comment by pascalgn** [comment]
This should be fixed in the latest release!

**Comment by pascalgn** [comment]
I'm closing this now, because I think it's fixed. If you disagree, feel free to re-open! 👍
