### ISSUE TITLE
Complete successfully if PR is already merged

### ISSUE THREAD

**Issue by mattsb42** [pascalgn/automerge-action#43]
I have several repos that have CI tests that take a rather long time to run. Because of this, I ramped up both the `MERGE_RETRIES` and `MERGE_RETRY_SLEEP` values to avoid the action timing out before all of the checks are complete. However, this uncovered another edge case: if multiple events trigger this action on the same PR, you will end up with multiple instances of the action all running at the same time. This results in one of these actions closing the PR and the others just hanging out until they time out.

Ideally, it would be nice if this could look for other instances of this action for this PR, but IDK how complex that would be. What seems like a relatively simple workaround for this, though, would be simply check to see if the PR has already been merged and exit successfully if so.

**Comment by pascalgn** [comment]
I think it's a rare issue, but we should still consider the current PR state during retries. Thanks for reporting this!

**Comment by pascalgn** [comment]
This should be fixed now in the latest release!

**Comment by mattsb42** [comment]
I updated to v0.7.0 and it looks like it is having the desired effect, but something after that appears to be breaking.

> INFO  Event name: pull_request
INFO  Skipping PR update, required label missing: automerge
INFO  Merging PR #162 bump automerge to v0.7.0
INFO  PR is probably ready: mergeable_state: unknown
ERROR m.contains is not a function


full logs attached
[4ImZnwOFbLVnyVZMmdcuX2FZ3hPF3NrOHXfmTvjULn8amGJcoQ.txt](https://github.com/pascalgn/automerge-action/files/4057623/4ImZnwOFbLVnyVZMmdcuX2FZ3hPF3NrOHXfmTvjULn8amGJcoQ.txt)

**Comment by mattsb42** [comment]
whoops...I spoke too soon; the thing succeeding that I saw was the auto-approver, not the auto-merger :( This is in fact failing.

**Comment by pascalgn** [comment]
Ah, thanks for the report! That was a bug, I just fixed it in the latest release 👍

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this if you disagree or if there are any other problems! 👍
