### ISSUE TITLE
Set commit author to PR author

### ISSUE THREAD

**Issue by mjarvis** [pascalgn/automerge-action#58]
Currently the `github-actions` bot takes over as committer. It would be helpful to add an `author` specification to the commit which adds the PR creator as an author.

Potentially as a further extension, this could use the `Co-authored-by:` system to add every person who contributed a commit to the PR.

**Comment by pascalgn** [comment]
I think this is quite important when merging via squash. For rebase merges or when a merge commit is created, I think it would be confusing.

Unfortunately, this is currently not supported by GitHub, there is no author field when merging: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button and https://developer.github.com/v4/input_object/mergepullrequestinput/

**Comment by mjarvis** [comment]
Looks like somewhere along the line this started working the way I've expected. It changed from `github-actions` bot committing to a joint commit, and now it says the correct author and the committer is github, so, someone up the line fixed it!
