### ISSUE TITLE
Changes in the PR status don't retrigger the action 

### ISSUE THREAD

**Issue by oreporan** [pascalgn/automerge-action#59]
We use codefresh and Teamcity that send a status to the PR (Pending, failed, success)

I notice when the CI sends a success status, the action doesn't rerun

Is that expected?

**Comment by pascalgn** [comment]
Is this possibly related to #7?

**Comment by pascalgn** [comment]
I think this is fixed now with #7 / #60. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
