### ISSUE TITLE
add support for check_run, check_suite ?

### ISSUE THREAD

**Issue by brad-decker** [pascalgn/automerge-action#7]
I need to hook into merge when check_run or check_suite actions are called because we use circle ci with github checks and it doesn't post status updates to the commits to trigger on 'status' when this feature is enabled. Thoughts? 

![image](https://user-images.githubusercontent.com/4448075/61556026-61ee5800-aa26-11e9-8903-e0da7f36d293.png)

**Comment by bjchambers** [comment]
Any update on this? It would be helpful for running in response to CircleCI checks.

**Comment by pascalgn** [comment]
Sorry, I thought I had already replied!

I'm not sure about this feature: We're also using Circle CI, and when a build finished, the `status` event is triggered just fine. As it says in the [documentation](https://developer.github.com/v3/repos/statuses/):
>As an example, one common use is for continuous integration services to mark commits as passing or failing builds using status.

**Comment by pascalgn** [comment]
By the way, I'm not against this feature. There's already a PR #8, but no reply there so far

**Comment by pascalgn** [comment]
This still isn't fixed, but blake-newman was kind enough to raise the issue in the GitHub community forum, maybe it will be addressed by GH at some point: https://github.community/t5/GitHub-Actions/New-Trigger-is-mergable-state/m-p/36908

**Comment by pascalgn** [comment]
I think this was fixed with #60. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍

**Comment by shugybugy-assaf** [comment]
@pascalgn For protected branches it still does not merge.

**Comment by pascalgn** [comment]
Are you sure that's related to the check_run/check_suite events? Or is it a separate issue?
