### ISSUE TITLE
Refetch pull request data after Github computes mergeability

### ISSUE THREAD

**Issue by lottamus** [pascalgn/automerge-action#70]
## Summary

I've noticed throughout this repo we're using the `mergeable_state` attribute instead of `mergeable`. There is a case where `mergeable_state` is "unknown" and `mergeable` is `null` while Github is  computes the `mergeable_state` in a background job. This causes issues in some of the logic in this repo where we assume the PR is ready to be merged when we should actually wait and retry.

This is likely causing the same issue described here https://github.com/pascalgn/automerge-action/issues/47.

According to Github's API docs: https://developer.github.com/v3/pulls/#response-1

> The value of the `mergeable` attribute can be `true`, `false`, or `null`. If the value is `null`, then GitHub has started a background job to compute the mergeability. After giving the job time to complete, resubmit the request. When the job finishes, you will see a non-null value for the `mergeable` attribute in the response. If `mergeable` is `true`, then `merge_commit_sha` will be the SHA of the test merge commit.

## Solution

[When we're checking for mergeability](https://github.com/pascalgn/automerge-action/blob/master/lib/update.js#L78), we should set a timeout before re-fetching the pull request data to give time for Github to finish their background job. 

https://github.com/pascalgn/automerge-action/blob/master/lib/update.js#L109-L124

```javascript
async function pullRequestState(octokit, pullRequest) {
  if (pullRequest.mergeable == null || !pullRequest.mergeable_state) {
    // We can probably use MERGE_RETRY_SLEEP and also need to keep track of the number of retries so we don't go forever
    await sleep(10000)

    // Refetch the pull request data
    const fullPullRequest = await fetchPullRequest(octokit, pullRequest);

    // Recheck pull request state
    return pullRequestState(octokit, fullPullRequest);
  } else {
    return pullRequest.mergeable_state;
  }
};

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function fetchPullRequest(octokit, pullRequest) {
  logger.debug("Getting pull request info for", pullRequest.number, "...");
  const { data: fullPullRequest } = await octokit.pulls.get({
    owner: pullRequest.base.repo.owner.login,
    repo: pullRequest.base.repo.name,
    pull_number: pullRequest.number
  });

  logger.trace("Full PR:", fullPullRequest);

  return fullPullRequest;
}
```

**Comment by pascalgn** [comment]
I have added two new options, `UPDATE_RETRIES` and `UPDATE_RETRY_SLEEP`, in https://github.com/pascalgn/automerge-action/releases/tag/v0.8.2

I think this could fix the issue. Please let me know if there are any problems! Thanks!

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
