### ISSUE TITLE
PRs getting merged even if token is non-administrative and tests have not passed

### ISSUE THREAD

**Issue by gilbertl** [pascalgn/automerge-action#71]
Hi,

Starting sometime yesterday, we're seeing PRs tagged "automerge" get automerged even though

- the Github Token we're using doesn't have administrative rights
- the PR has not passed all the tests
- the PR doesn't have reviewer approval and the branch is protected

Wondering if others are seeing the same issue; please advice on what information to share to help debug.

**Comment by pascalgn** [comment]
Could you share screenshots of the branch protection rules? Also, could you share a link to the relevant PRs, or, if that's not possible, the output of the automerge action run that merged the PR?

**Comment by gilbertl** [comment]
Got this e-mail from GitHub today. I think this explains it:

> We’re writing to let you know that on April 15, non-admin repository members were briefly able to override branch protection settings and merge pull requests when branch protection rules weren't met. Specifically, these non-admin users were already allowed to push to protected branches.

**Comment by pascalgn** [comment]
Ah, that explains it! Thanks for the update! 👍
