### ISSUE TITLE
Only merge PRs targeting specific branch

### ISSUE THREAD

**Issue by lwasyl** [pascalgn/automerge-action#94]
I'd like to configure the action such that it merges only if the PR targets `master`. If `automerge` label is present and the target branch is changed to `master` later, it should merge it. Is it possible with current configuration options?

**Comment by pascalgn** [comment]
Yes, this should already be possible using `if` (available for all GH actions) https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif

**Comment by lwasyl** [comment]
Ah, I was looking for some configuration within the action and didn't think I can simply not run it :) Thanks!
