### ISSUE TITLE
bug: Merge Fails if workflow applied required label

### ISSUE THREAD

**Issue by TGTGamer** [pascalgn/automerge-action#97]
When using auto merge in the same workflow as something like [actions/labeler](https://github.com/actions/labeler) the job fails to merge due to `required label missing: automerge`. 

Workflow link: https://github.com/TGTGamer/.github/blob/b4e1a53e7b5faa73d25b7b25a93fd1037d100bd4/.github/workflows/pull.yml#L150
Failed job link: https://github.com/TGTGamer/.github/runs/887396777
Valid pull request which failed:  https://github.com/TGTGamer/.github/pull/49

Console Output: 
```log
INFO  Event name: pull_request
INFO  Skipping PR update, required label missing: automerge
INFO  Skipping PR merge, required label missing: automerge
```

#78 -- might be a fix if merged and tested

**Comment by ryandy** [comment]
Similarly, the action's knowledge of PR labels can be out-of-date if the action is performed at the end of a multi-job workflow. For example, I'd like to run automerge-action after a series of build/test jobs that take about 10 minutes. If someone manually adds the automerge label during that time, automerge-action won't know, and will act based on the state of PR labels from when the workflow began.

I agree that #78 seems to be the fix. I tried it out locally and it worked for my use case. @pascalgn any plans to move forward with that PR?

**Comment by pascalgn** [comment]
I just merged #78! 👍

**Comment by ryandy** [comment]
Great, thanks!

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
