### ISSUE TITLE
Allow deleting merge branches except some branches

### ISSUE THREAD

**Issue by AnandChowdhary** [pascalgn/automerge-action#99]
We have an interesting use case where we merge feature branches to `master`, and then `master` to `production`. In this case, enabling `MERGE_DELETE_BRANCH` means it correctly deletes feature branches after merging them, but also deletes `master` after merging it.

I'd love it if we could add a feature where we could set `MERGE_DELETE_BRANCH` to `true`, but also have a `DELETE_BRANCHES` parameter, perhaps like:

```yml
MERGE_DELETE_BRANCH: true
DELETE_BRANCHES: *,!master
```

i.e., "delete all branches after merging, but not `master`"

**Comment by AArnott** [comment]
Why not just use the github repo setting to delete HEAD branches after PRs? It won't delete branches when branch protections are in place, which you should surely have for `master`, right?

**Comment by AnandChowdhary** [comment]
Unfortunately, in this very specific case, I don't have branch protections enabled because this organization is on the Free plan and this is a private repository (see [About protected branches](https://docs.github.com/en/github/administering-a-repository/about-protected-branches)).

Otherwise, we would be able to use GitHub's "delete branch after merge" feature, but opted for this Action because we're able to configure otherwise Pro features 😉

**Comment by AnandChowdhary** [comment]
Plus, the use case is the ensure `production` and `master` are never deleted after merges, so it's sort of a "de facto branch protection" that this action may enable. I'm assuming the `master` branch protection is built-in, even if we're on the Free plan, since it's the default branch, but we'll want to enable this feature for other branches too.

**Comment by AnandChowdhary** [comment]
I've made a PR #100 (yay for 100!), that adds support for this — having a custom-defined list of protected branches that this action doesn't delete.
